# Generated by Django 3.2.3 on 2021-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0002_auto_20210607_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
